#!/bin/sh

target_link=/usr/local/bin/hog
if [ -L $target_link ]; then
  echo "Symbolic link already exists: ${target_link}; skipping installation."
  exit 0
fi

cd $(dirname "$0")
ln -s $(pwd)/hog $target_link
if [ $? -ne 0 ]; then
  echo "Failed to create symbolic link; existing."
  exit 1
fi

echo "Installed to $target_link"
